(ns mine-sweep.ui.resources.svg)

(def mine
  "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"1000px\" height=\"1000px\" viewBox=\"0 0 100 100\" preserveAspectRatio=\"xMidYMid meet\" ><rect id=\"svgEditorBackground\" x=\"0\" y=\"0\" width=\"100\" height=\"100\" style=\"fill: none; stroke: none;\"/><circle id=\"e1_circle\" cx=\"50\" cy=\"55\" style=\"fill:black;stroke:none;stroke-width:0;\" r=\"27\"/><path d=\"M60,35L70 15\" style=\"fill:none;stroke:black;stroke-width:4;\"/><path d=\"M70,15L72 11\" style=\"fill:none;stroke:red;stroke-width:4;\"/></svg>")

(def flag
  "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"1000px\" height=\"1000px\" viewBox=\"0 0 100 100\" preserveAspectRatio=\"xMidYMid meet\" ><rect id=\"svgEditorBackground\" x=\"0\" y=\"0\" width=\"100\" height=\"100\" style=\"fill: none; stroke: none;\"/><polygon id=\"svgEditorShapeDefs\" points=\"20 10,20 60,80 35\" style=\"fill:darkred;stroke:none;vector-effect:non-scaling-stroke;stroke-width:0;\"/><line id=\"e5_line\" x1=\"20\" y1=\"10\" x2=\"20\" y2=\"85\" style=\"stroke:black;fill:none;stroke-width:10;\"/></svg>")

(def smile
  "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 100 100\" preserveAspectRatio=\"xMidYMid meet\"><rect id=\"svgEditorBackground\" x=\"0\" y=\"0\" width=\"100\" height=\"100\" style=\"fill: none; stroke: none;\"/><circle id=\"e1_circle\" cx=\"50\" cy=\"50\" style=\"fill:yellow;stroke:black;stroke-width:0;\" r=\"50\"/><circle id=\"e2_circle\" cx=\"30\" cy=\"35\" style=\"fill:black;stroke:none;stroke-width:1;\" r=\"8\"/><circle id=\"e3_circle\" cx=\"70\" cy=\"35\" style=\"fill:black;stroke:none;stroke-width:1;\" r=\"8\"/><path d=\"M25,65Q50 90,75 65\" style=\"fill:none;stroke:black;stroke-width:5;\" id=\"e4_circleArc\"/></svg>")

(def working
  "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 100 100\" preserveAspectRatio=\"xMidYMid meet\"><rect id=\"svgEditorBackground\" x=\"0\" y=\"0\" width=\"100\" height=\"100\" style=\"fill: none; stroke: none;\"/><circle id=\"e1_circle\" cx=\"50\" cy=\"50\" style=\"fill:yellow;stroke:none;stroke-width:0;\" r=\"50\"/><circle id=\"e2_circle\" cx=\"30\" cy=\"35\" style=\"fill:black;stroke:none;stroke-width:0;\" r=\"8\"/><circle id=\"e3_circle\" cx=\"70\" cy=\"35\" style=\"fill:black;stroke:none;stroke-width:0px;\" r=\"8\"/><circle id=\"e4_circle\" cx=\"50\" cy=\"75\" style=\"fill:none;stroke:black;stroke-width:1px;\" r=\"10\"/></svg>")

(def faint
  "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 100 100\" preserveAspectRatio=\"xMidYMid meet\" ><rect id=\"svgEditorBackground\" x=\"0\" y=\"0\" width=\"100\" height=\"100\" style=\"fill: none; stroke: none;\"/><circle id=\"e1_circle\" cx=\"50\" cy=\"50\" style=\"fill:yellow;stroke:none;stroke-width:0;\" r=\"50\"/><circle id=\"e2_circle\" cx=\"30\" cy=\"35\" style=\"fill:none;stroke:black;stroke-width:1px;\" r=\"15\"/><circle id=\"e3_circle\" cx=\"30\" cy=\"35\" style=\"fill:none;stroke:black;stroke-width:1px;\" r=\"10\"/><circle id=\"e2_circle\" cx=\"30\" cy=\"35\" style=\"fill:none;stroke:black;stroke-width:1px;\" r=\"5\"/><circle id=\"e4_circle\" cx=\"70\" cy=\"35\" style=\"fill:none;stroke:black;stroke-width:1px;\" r=\"15\"/><circle id=\"e5_circle\" cx=\"70\" cy=\"35\" style=\"fill:none;stroke:black;stroke-width:1px;\" r=\"10\"/><circle id=\"e6_circle\" cx=\"70\" cy=\"35\" style=\"fill:none;stroke:black;stroke-width:1px;\" r=\"5\"/><path d=\"M25,80Q50 50,75 80\" style=\"fill:none;stroke:black;stroke-width:2px;\" id=\"e7_circleArc\"/></svg>")


(def cool
  "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 100 100\" preserveAspectRatio=\"xMidYMid meet\" ><rect id=\"svgEditorBackground\" x=\"0\" y=\"0\" width=\"100\" height=\"100\" style=\"fill: none; stroke: none;\"/><circle id=\"e1_circle\" cx=\"50\" cy=\"50\" style=\"fill:yellow;stroke:none;stroke-width:0;\" r=\"50\"/><circle id=\"e2_circle\" cx=\"30\" cy=\"35\" style=\"fill:black;stroke:black;stroke-width:0;\" r=\"15\"/><circle id=\"e4_circle\" cx=\"70\" cy=\"35\" style=\"fill:black;stroke:black;stroke-width:0;\" r=\"15\"/><path d=\"M17,35L5 28.2\" style=\"fill:none;stroke:black;stroke-width:3;\" id=\"l1\"/><path d=\"M83,35L95 28.2\" style=\"fill:none;stroke:black;stroke-width:3;\" id=\"l2\"/><path d=\"M30,36L70 36\" style=\"fill:none;stroke:black;stroke-width:3;\" id=\"l3\"/><path d=\"M30,75Q50 90,77 68\" style=\"fill:none;stroke:black;stroke-width:3;\" id=\"e4_circleArc\"/></svg>")
